# -*- coding:utf-8 -*-
'''
Author: Grays (Generated by AI)
Date: 2023-10-27
Description: 样品扫码出库后端逻辑
'''
from any import *
from .model import *
import json
import datetime
import time




def update_model(model_obj, data_dict, mapping=None):
    """
    批量给 ORM 模型赋值
    :param model_obj: ORM 实例对象
    :param data_dict: 前端传来的字典数据
    :param mapping: 字段映射表 { '数据库字段': '前端Key' }
    """
    if mapping:
        for db_field, json_key in mapping.items():
            if json_key in data_dict:
                setattr(model_obj, db_field, data_dict.get(json_key))
    else:
        # 如果没有映射表，则尝试匹配同名字段
        for key, value in data_dict.items():
            if hasattr(model_obj, key):
                setattr(model_obj, key, value)



# ---------------------------------------------------------------------
# 接口1：手动输入条码查询
# 对应前端: do_manual_submit -> /api/outstock/sample_code
# 前端期望返回结构: res.data.data (行数据) 和 res.data.fields (虽然前端没用到fields渲染，但代码里写了接收)
# ---------------------------------------------------------------------
@any_route('/api/saier/instock/sample_code/search', methods=['POST'])
@require_token
async def api_saier_instock_sample_code(request):
    s = Session()
    try:
        j = await request.json()
        code = j.get('code', '').strip()
        
        if not code:
            return json_result(-1, '条码不能为空')

        # 查询样品档案 (ypgl)
        product = s.query(ypgl).filter(
            or_(ypgl.lxm == code, ypgl.cpbh == code)
        ).first()

        if not product:
            return json_result(-1, '未找到该条码对应的样品资料')


        row = alchemy_object_to_dict(product)
        return json_result(1, '查询成功', {
            'data': row,
      
        })
    except Exception as e:
        logger.error(trace_error())
        return json_result(-1, f'查询异常: {str(e)}')
    finally:
        s.close()


# ---------------------------------------------------------------------
# 接口2：扫描枪连续扫码查询
# 对应前端: on_barcode_scan -> /api/moduo/sample/info
# 前端期望返回结构: res.data 直接就是产品对象
# ---------------------------------------------------------------------
@any_route('/api/saier/sample/get_info', methods=['POST'])
@require_token
async def api_saier_sample_info(request):
    s = Session()
    try:
        j = await request.json()
        code = j.get('barcode', '').strip()
        
        if not code:
            return json_result(-1, '无效的条码')

        product = s.query(ypgl).filter(
            or_(ypgl.lxm == code, ypgl.cpbh == code)
        ).first()

        if not product:
            return json_result(-1, '条码未找到')

        row = alchemy_object_to_dict(product)
        formatted_data = format_product_data(row)

        # 注意：这里直接返回 formatted_data 作为 data，不需要包裹在 {'data': ...} 里
        # 因为 json_result 会把第三个参数作为 res.data 返回
        return json_result(1, '查询成功', formatted_data)

    except Exception as e:
        logger.error(trace_error())
        return json_result(-1, '扫描异常')
    finally:
        s.close()


# ---------------------------------------------------------------------
# 接口3：提交出库单
# 对应前端: do_submit -> /api/saier/sample/outstock_submit  

#  样品出库管理 ypckgl   样品出库管理出库详情 子表 ypxjglsheet 实现新增

# ---------------------------------------------------------------------
@any_route('/api/saier/sample/instock_submit', methods=['POST'])
@require_token
async def api_submit_instock_info(request):
    s = Session()
    try:
        j = await request.json()
        user = request.current_user
        main_info = j.get('sample_instock_main', {})
        details = j.get('sample_instock_details', [])

        if not details:
            return json_result(-1, '请添加样品信息')

        # --- 映射配置 ---
        # 主表映射：{ 数据库字段 : 前端Key }
        # MAIN_MAP = {
        #     'czry': 'Personnel', 'czsj': 'OpTime', 'czr': 'Operator', 'laiy': 'Source'
        # }
        # # 子表映射
        # DETAIL_MAP = {
        #     'rksl': 'InStockQty', 'bzh': 'detailRemark', 'cpbh': 'cpbh',
        #     'zwpm': 'zwpm', 'lxm': 'lxm', 'laiy': 'Source', 
        #     'sccj': 'company_name', 'cjID': 'company_id'
        # }
        # # 样品详情子表映射 (ypglsheet1)
        # SAMPLE_SHEET_MAP = {
        #     'cpbh': 'cpbh', 'zwpm': 'zwpm', 'yytp': 'yytp', 'ywpm': 'ywpm',
        #     'cpgg': 'cpgg', 'cpfl': 'cpfl', 'cgdj': 'cgdj', 'zxcgl': 'zxcgl',
        #     'cjID': 'company_id', 'sccj': 'company_name', 'cgry': 'cgry',
        #     'rksl': 'InStockQty', 'lxm': 'lxm', 'bzh': 'detailRemark'
        # }

        #1. 生成入库产品信息表 
        create_time=time.strftime("%Y-%m-%d %H:%M:%S")
        #样品入库管理表
        yprkgl_rid=get_uuid()
        yprkgl_m = yprkgl() 
        yprkgl_m.rid = yprkgl_rid
        yprkgl_m.uid = user.rid
        yprkgl_m.ctime=create_time

        yprkgl_m.czry = main_info.get('Personnel') # 人员
        yprkgl_m.czsj = main_info.get('OpTime') # 操作时间
        yprkgl_m.czr =  main_info.get('Operator')      # 操作人
        yprkgl_m.laiy=main_info.get('Source') # 来源
        yprkgl_m.wyzd = yprkgl_rid # 唯一字段
        yprkgl_m.czsjxq = create_time 
       
        # sample_in_stock_total=0


        #2.生成 入库管理中的子表 yprkglsheet  样品入库管理详情
        for detail in details:
            unique_field=get_uuid()
            yprkglsheet_m = yprkglsheet()
            yprkglsheet_m.rid = unique_field
            yprkglsheet_m.pid = yprkgl_rid
            yprkglsheet_m.rkrq = main_info.get('OpTime') # 操作时间
            yprkglsheet_m.rksl = detail.get('InStockQty') # 入库数量
            yprkglsheet_m.czry = main_info.get('Personnel') # 人员
            yprkglsheet_m.bzh = detail.get('detailRemark') # 备注
            yprkglsheet_m.czr = main_info.get('Operator') # 操作人
            yprkglsheet_m.lxm = detail.get('lxm') # 
            yprkglsheet_m.cpbh = detail.get('cpbh') # 产品编码
            yprkglsheet_m.zwpm = detail.get('zwpm') # 产品名称
            yprkglsheet_m.wyzd = unique_field # 唯一字段
            yprkglsheet_m.laiy = main_info.get('Source') # 来源
            yprkglsheet_m.sccj = detail.get('company_name') # 生产厂家
            yprkglsheet_m.cjID = detail.get('company_id') # 供应商
            s.add(yprkglsheet_m)

            ypgl_sample= s.query(ypgl).filter(ypgl.lxm == detail.get('lxm')).first()
            ypgl_rid=ypgl_sample.rid
            #入库数量的管理 
            in_qty=int(detail.get('InStockQty'))

            ypgl_sample.ljrk+=in_qty
            ypgl_sample.kcsl += in_qty
            #样品管理中的子表 入库详情
            ypglsheet_m= ypglsheet1()
            ypglsheet_m.rid = get_uuid()
            ypglsheet_m.pid = ypgl_rid  # 关联主表ID
            ypglsheet_m.cpbh= detail.get('cpbh') # 产品编码
            ypglsheet_m.zwpm= detail.get('zwpm') # 产品名称
            ypglsheet_m.yytp= detail.get('yytp') # 产品图品
            ypglsheet_m.ywpm= detail.get('ywpm') # 英文品名
            ypglsheet_m.cpgg= detail.get('cpgg') # 产品规格
            ypglsheet_m.cpfl= detail.get('cpfl') # 产品分类

            ypglsheet_m.cgdj= detail.get('cgdj') # 采购单价
            ypglsheet_m.zxcgl= detail.get('zxcgl') # 起订量
            ypglsheet_m.cjID= detail.get('company_id') # 供应商
            ypglsheet_m.sccj= detail.get('company_name') # 生产厂家
            ypglsheet_m.cgry= detail.get('cgry') # 采购人
            ypglsheet_m.rksl= detail.get('InStockQty') # 入库数量
            ypglsheet_m.lxm= detail.get('lxm') 
            ypglsheet_m.rkrq= main_info.get('OpTime') # 操作时间
            ypglsheet_m.czry= main_info.get('Personnel') # 人员
            ypglsheet_m.laiy= main_info.get('Source') # 来源
            ypglsheet_m.bzh= detail.get('detailRemark') # 备注
            ypglsheet_m.czr= main_info.get('Operator') # 操作人
            # sample_in_stock_total+=int(detail.get('InStockQty'))
            
            s.add(ypglsheet_m)
            s.add(ypgl_sample)
        


        s.add(yprkgl_m)

        s.commit()
        return json_result(1, '提交成功',)

    except Exception as e:
        s.rollback()
        logger.error(trace_error())
        return {"code": -1, "msg": trace_error()}
    finally:
        s.close()




#获取生产厂家 或者 厂商编码
@any_route('/api/saier/sample/company_search', methods=['POST'])
@require_token
async def api_company_search(request):
    s = Session()
    #只对专属产品中的生产厂家进行了查询
    try:
        j = await request.json()
        keyword = j.get('keyword', '')
        # 同时对生产厂家和厂商编码进行模糊查询
        company_list = s.query(zycs).filter(
            or_(
                zycs.company_name.like(f'%{keyword}%'),
                zycs.cs_id.like(f'%{keyword}%')
            )
        ).all()
        return json_result(1, '查询成功', [{'name': c.company_name, 'id': c.cs_id} for c in company_list])
    except Exception as e:
        logger.error(trace_error())
        return {"code": -1, "msg": trace_error()}
    finally:
        s.close()





