# -*- coding:utf-8 -*-
'''
Author: Grays (Generated by AI)
Date: 2023-10-27
Description: 样品扫码出库后端逻辑
'''
from any import *
from .model import *
import json
import datetime
import time

# ---------------------------------------------------------------------  
# 辅助函数：将数据库 ypgl 对象转换为前端需要的字典格式
# ---------------------------------------------------------------------  
def format_product_data(row_dict):
    """
    将 ypgl 的数据库字段映射为前端 scan_out_stock 组件需要的字段
    假设数据库字段: cpbh(编号), lxm(条码), pm(品名), rid(ID)
    """
    return {
        "rid": row_dict.get('rid'),
        "ItemNo": row_dict.get('cpbh'),           # 对应前端 ItemNo
        "Barcode": row_dict.get('lxm'),           # 对应前端 Barcode
        "CHNItemName": row_dict.get('zwpm'),        # 对应前端 CHNItemName
        "OutStockQty": 1,                         # 默认数量
        "Destination": "",                        # 占位，由前端主表填充
        "Remarks": ""
    }

# ---------------------------------------------------------------------
# 接口1：手动输入条码查询
# 对应前端: do_manual_submit -> /api/outstock/sample_code
# 前端期望返回结构: res.data.data (行数据) 和 res.data.fields (虽然前端没用到fields渲染，但代码里写了接收)
# ---------------------------------------------------------------------
@any_route('/api/saier/outstock/sample_code/search', methods=['POST'])
@require_token
async def api_saier_outstock_sample_code(request):
    s = Session()
    try:
        j = await request.json()
        code = j.get('code', '').strip()
        
        if not code:
            return json_result(-1, '条码不能为空')

        # 查询样品档案 (ypgl)
        product = s.query(ypgl).filter(
            or_(ypgl.lxm == code, ypgl.cpbh == code)
        ).first()

        if not product:
            return json_result(-1, '未找到该条码对应的样品资料')


        row = alchemy_object_to_dict(product)
   
        # 补充：如果是手动扫码，前端代码有一句 row.closed = true，后端也可以带上
        # formatted_data['closed'] = True

        # 构造 fields (前端逻辑中有 this.fields = res.data.fields)
        # 虽然前端模板是写死的，但为了不报错，返回一个空列表或基础结构
  

        return json_result(1, '查询成功', {
            'data': row,
      
        })
    except Exception as e:
        logger.error(trace_error())
        return json_result(-1, f'查询异常: {str(e)}')
    finally:
        s.close()


# ---------------------------------------------------------------------
# 接口2：扫描枪连续扫码查询
# 对应前端: on_barcode_scan -> /api/moduo/sample/info
# 前端期望返回结构: res.data 直接就是产品对象
# ---------------------------------------------------------------------
@any_route('/api/saier/sample/get_info', methods=['POST'])
@require_token
async def api_saier_sample_info(request):
    s = Session()
    try:
        j = await request.json()
        code = j.get('barcode', '').strip()
        
        if not code:
            return json_result(-1, '无效的条码')

        product = s.query(ypgl).filter(
            or_(ypgl.lxm == code, ypgl.cpbh == code)
        ).first()

        if not product:
            return json_result(-1, '条码未找到')

        row = alchemy_object_to_dict(product)
        formatted_data = format_product_data(row)

        # 注意：这里直接返回 formatted_data 作为 data，不需要包裹在 {'data': ...} 里
        # 因为 json_result 会把第三个参数作为 res.data 返回
        return json_result(1, '查询成功', formatted_data)

    except Exception as e:
        logger.error(trace_error())
        return json_result(-1, '扫描异常')
    finally:
        s.close()


# ---------------------------------------------------------------------
# 接口3：提交出库单
# 对应前端: do_submit -> /api/saier/sample/outstock_submit  

#  样品出库管理 ypckgl   样品出库管理出库详情 子表 ypxjglsheet 实现新增

# ---------------------------------------------------------------------
@any_route('/api/saier/sample/outstock_submit', methods=['POST'])
@require_token
async def api_submit_outstock_info(request):
    s = Session()
    try:
        j = await request.json()
        user = request.current_user
        
        main_info = j.get('sample_outstock_main', {}) # 样品出库管理主表
        details = j.get('sample_outstock_details', []) # 样品出库管理子表   其中涉及到产品的很多详细信息

        if not details:
            return json_result(-1, '没有出库明细，无法提交')

        # 1. 生成主表对象 (假设表名为 ypck - 样品出库)
        # 你需要在 model.py 中定义 class ypckgl(Base): ...
        create_time=time.strftime("%Y-%m-%d %H:%M:%S")
        ypckgl_m = ypckgl() 
        ypckgl_rid = get_uuid()
        ypckgl_m.rid = ypckgl_rid
        ypckgl_m.uid = user.rid
        ypckgl_m.ctime=create_time
        # 填充主表字段
        ypckgl_m.czry = main_info.get('Personnel') # 领用人
        ypckgl_m.czsj = main_info.get('OpTime') # 操作时间
        ypckgl_m.czr =  main_info.get('Operator')      # 操作人
        
        ypckgl_m.wyzd = ypckgl_rid # 唯一字段
        #操作时间详情   czsjxq
        # ypckgl_m.czsjxq = time.strftime("%Y-%m-%d %H:%M:%S")    
        ypckgl_m.ypqx = main_info.get('Destination') # 样品去向
        ypckgl_m.bzh = main_info.get('Remarks') # 备注
        #数量合计是计算字段
        # ypckgl_m.slhj = main_info.get('totalQty') # 数量合计
        #来访日期 lfrq
        #公司名称 company_name
        
        #样品出库管理中的 数量合计字段
        sample_out_stock_total=0

        # 2. 生成子表明细 ( ypxjglsheet - 样品出库管理 中的出库详情)

        for  item in (details):
            ypxjglsheet_m = ypxjglsheet()  
            ypxjglsheet_m.rid = get_uuid()
            ypxjglsheet_m.pid = ypckgl_rid  # 关联主表ID
            ypxjglsheet_m.riqi= main_info.get('OpTime') # 操作时间
            ypxjglsheet_m.ljck = item.get('OutStockQty') # 出库数量
            ypxjglsheet_m.jldw = item.get('jldw')      # 单位
            ypxjglsheet_m.ypqx = main_info.get('Destination')    # 样品去向
            ypxjglsheet_m.czry = main_info.get('Personnel') # 领用人
            ypxjglsheet_m.bzh = main_info.get('Remarks') # 备注
            ypxjglsheet_m.ctime=create_time
            
            ypxjglsheet_m.czr= main_info.get('Operator') # 操作人
            ypxjglsheet_m.cpbh = item.get('cpbh') # 产品编号
            ypxjglsheet_m.zwpm = item.get('zwpm') # 中文品名
            ypxjglsheet_m.lxm = item.get('lxm') # 条形码   
            ypxjglsheet_m.sfhx= item.get('writtenoff') # 是否核销
            
            s.add(ypxjglsheet_m)

            ypgl_sample= s.query(ypgl).filter(ypgl.lxm == item.get('lxm')).first()


            ypgl_rid= ypgl_sample.rid
            out_qty = int(item.get('OutStockQty', 0)) # 出库数量
            current_qckc = int(ypgl_sample.qckc or 0) # 期初库存
            current_ljrk = int(ypgl_sample.ljrk or 0) # 累计入库
            current_ljxj = int(ypgl_sample.ljxj or 0) # 累计下架
            current_ljck = int(ypgl_sample.ljck or 0) # 累计出库

            # 计算当前实际可用库存
            available_stock = current_qckc + current_ljrk - current_ljxj - current_ljck

            if out_qty > available_stock:
                s.rollback()
                return json_result(-1, f"产品【{ypgl_sample.zwpm}】库存不足！当前库存：{available_stock}，申请出库：{out_qty}")

            # 4. 执行更新
            # 更新累计出库量
            ypgl_sample.ljck = current_ljck + out_qty
            # 更新实时库存字段
            ypgl_sample.kcsl = current_qckc + current_ljrk - current_ljxj - ypgl_sample.ljck
        
            #对于item 来讲  要去对应的lxm 下的ypgl中找数据 然后新增 子表 ypglsheet
            # 子表新增之后 要统计累积出库 

            ypglsheet_m= ypglsheet()
            ypglsheet_m.rid = get_uuid()
            ypglsheet_m.pid = ypgl_rid  # 关联主表ID
            ypglsheet_m.riqi= main_info.get('OpTime') # 操作时间
            ypglsheet_m.ljck = item.get('OutStockQty') # 出库数量
            ypglsheet_m.ctime=create_time

            ypglsheet_m.jldw = item.get('jldw')      # 单位
            ypglsheet_m.ypqx = main_info.get('Destination')    # 样品去向
            ypglsheet_m.czry = main_info.get('Personnel') # 领用人
            ypglsheet_m.bzh = main_info.get('Remarks') # 备注
            ypglsheet_m.czr= main_info.get('Operator') # 操作人
            ypglsheet_m.zwpm = item.get('zwpm') # 中文品名
            ypglsheet_m.lxm = item.get('lxm') # 条形码   
            ypglsheet_m.sfhx= item.get('writtenoff') # 是否核销
            sample_out_stock_total+=int(item.get('OutStockQty'))
            s.add(ypglsheet_m)
            s.add(ypgl_sample)  #更新主表
            
        #样品管理表中的 累计出库 以及 库存数量 都是计算列 是根据ypglsheet子表进行判断的\  
        ypckgl_m.slhj=sample_out_stock_total
        s.add(ypckgl_m)

        # 仅实现了后端数据的新增 但是平台前端 需要重新更新数据  



        s.commit()
        return json_result(1, '提交成功',)

    except Exception as e:
        s.rollback()
        logger.error(trace_error())
        return {"code": -1, "msg": trace_error()}
    finally:
        s.close()